sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: "001106"
  qiniuoss:
    access-key: H2NJ7aOTfZQhsgbtMD1Py6LY0bAE4JFEDMwcWeAs
    secret-key: oVDDRpNkjIqVe4mH295Rc7Frq0_asPFN7tGHQuBP
    bucket-name: sky-take-out2024
  redis:
    host: localhost
    port: 6379
    database: 0
  wechat:
    appid: wx7d4c39835317d376
    secret: 8b86a18b1eb65705232c6fec8584978d